spring:
  data:
    mongodb:
      #uri: mongodb://user:password@localhost:27017/auth-db?retryWrites=false
      uri: mongodb://localhost:27017/auth-db

config:
  oauth2:
    ui-uri: http://localhost:4200/callback